import type { SUPPORTED_ADAPTERS } from './lib/utils.js'

/**
 * Generate router using the buildRouter pattern for better type inference
 *
 * Works with:
 * - @astrojs/cloudflare
 * - @astrojs/node
 * - @astrojs/vercel
 */
export function generateRouter(opts: {
    basePath: string
    relativeActionsPath: string
    adapter: (typeof SUPPORTED_ADAPTERS)[number]
}) {
    const { basePath, relativeActionsPath, adapter } = opts

    let exportedApp = `export default app`
    if (adapter === '@astrojs/netlify') {
        exportedApp = `export default handle(app)`
    }

    return `import type { HonoEnv, MergeActionKeyIntoPath } from '@gnosticdev/hono-actions/actions'
import { Hono } from 'hono'
import { cors } from 'hono/cors'
import { showRoutes } from 'hono/dev'
import { logger } from 'hono/logger'
import { prettyJSON } from 'hono/pretty-json'
import type { ExtractSchema, MergeSchemaPath } from 'hono/types'
${adapter === '@astrojs/netlify' ? "import { handle } from 'hono/netlify'" : ''}

async function buildRouter(){
    type ActionsWithKeyedPaths = MergeActionKeyIntoPath<typeof honoActions>
    type ActionSchema = ExtractSchema<ActionsWithKeyedPaths[keyof ActionsWithKeyedPaths]>
    const { honoActions} = await import('${relativeActionsPath}')
    const app = new Hono<HonoEnv, MergeSchemaPath<ActionSchema, '${basePath}'>>().basePath('${basePath}')

    app.use('*', cors(), logger(), prettyJSON())

    for (const [routeName, action] of Object.entries(honoActions)) {
        app.route(\`/\${routeName}\`, action)
    }

    return app
}

export type HonoRouter = Awaited<ReturnType<typeof buildRouter>>

const app = await buildRouter()
console.log('------- Hono Routes -------')
showRoutes(app)
console.log('---------------------------')
${exportedApp}`
}

/**
 * Injects the Hono router into the Astro API route handler at `src/pages/api/[...slug].ts`
 *
 * @param adapter - The adapter in use from the astro config
 *
 * For use with `@astrojs/cloudflare` adapter only (for now).a
 */
export const generateAstroHandler = (
    adapter: (typeof SUPPORTED_ADAPTERS)[number],
) => {
    switch (adapter) {
        case '@astrojs/cloudflare':
            return `
/// <reference types="./types.d.ts" />
// Generated by Hono Actions Integration
// adapter: ${adapter}
import type { APIContext, APIRoute } from 'astro'
import router from './router.js'

const handler: APIRoute<APIContext> = async (ctx) => {
    return router.fetch(
        ctx.request,
        ctx.locals.runtime.env, // required for cloudflare adapter
        ctx.locals.runtime.ctx, // required for cloudflare adapter
    )
}

export { handler as ALL }
`
        case '@astrojs/node':
        case '@astrojs/vercel':
            return `
/// <reference types="./types.d.ts" />
// Generated by Hono Actions Integration
// adapter: ${adapter}
import type { APIContext, APIRoute } from 'astro'
import router from './router.js'

const handler: APIRoute<APIContext> = async (ctx) => {
    return router.fetch(
        ctx.request,
    )
}

export { handler as ALL }
`
        case '@astrojs/netlify':
            return `
/// <reference types="./types.d.ts" />
// Generated by Hono Actions Integration
// adapter: ${adapter}
import type { APIContext, APIRoute } from 'astro'
import netlifyHandler from './router.js'

const handler: APIRoute<APIContext> = async (ctx) => {
    return netlifyHandler(ctx.request, ctx)
}

export { handler as ALL }
`
        default:
            throw new Error(`Unsupported adapter: ${adapter}`)
    }
}
/**
 * Generate Hono client code
 *
 * @param port - The port number for the dev server
 */
export const generateHonoClient = (port: number) => `
// Generated by Hono Actions Integration
import type { HonoRouter } from './router.js'
import { hc, parseResponse } from 'hono/client'
import type { DetailedError, ClientRequestOptions } from 'hono/client'

function getBaseUrl() {
    // client side can just use the base path
    if (typeof window !== 'undefined') {
        return '/'
    }

    // dev server (dev server) needs to know the port
    if (import.meta.env.DEV) {
        return 'http://localhost:${port}'
    }

    // server side (production) needs full url
    return import.meta.env.SITE ?? ''
}

export { parseResponse, hc as createHonoClient}
export type { DetailedError, ClientRequestOptions }
/**
 * Default hono client using the base url from the environment
 * **Note** if running in production, the \`siteUrl\` option from the astro config will be used.
 * If customization is needed, use the \`createHonoClient\` function instead.
 */
export const honoClient = createHonoClient<HonoRouter>(getBaseUrl())
`

export const generateIntegrationTypes = (adapter: (typeof SUPPORTED_ADAPTERS)[number]) => {
    // generic action types, only used for module augmentation
    let actionTypes = `
    // Generated by Hono Actions Integration
    declare module '@gnosticdev/hono-actions/actions' {
        interface Bindings { [key: string]: unknown }
        interface Variables { [key: string]: unknown }
        interface HonoEnv { Bindings: Bindings, Variables: Variables }
    }
    export {}
    `

    // generic client types
    let clientTypes = `
// Generated by Hono Actions Integration
declare module '@gnosticdev/hono-actions/client' {
    export const honoClient: typeof import('./client').honoClient
    export const parseResponse: typeof import('./client').parseResponse
    export const createHonoClient: typeof import('./client').createHonoClient
    export type DetailedError = import('./client').DetailedError
    export type ClientRequestOptions = import('./client').ClientRequestOptions
}
`
    switch (adapter) {
        // cloudflare uses Bindings and Variables passed in from the route handler
        case '@astrojs/cloudflare':
            actionTypes = `
// Generated by Hono Actions Integration
// keeping separate from the main types.d.ts to avoid clobbering package exports
declare module '@gnosticdev/hono-actions/actions' {
    interface Bindings extends Env { ASTRO_LOCALS: App.Locals }
    interface Variables { [key: string]: unknown }
    interface HonoEnv { Bindings: Bindings, Variables: Variables }
}
export {}
`
// add cloudflare only types
            clientTypes += `
type Runtime = import('@astrojs/cloudflare').Runtime<Env>

declare namespace App {
    interface Locals extends Runtime {}
}
`
            break
        default:

            break
    }
    return { actionTypes, clientTypes }
}